-- English fallback; no report, support, appeal or decision text is interpolated.
WITH seed(text_key, category, body) AS (
  VALUES
    ('admin.button.cancel', 'button', 'Cancel'),
    ('admin.button.confirm', 'button', 'Confirm action'),
    ('admin.confirm.prompt', 'message', 'Check the selected target and reason before confirming.'),
    ('admin.confirm.title', 'message', 'Confirm this action'),
    ('admin.outcome.failed', 'message', 'The action could not be completed. Try again later.'),
    ('admin.outcome.rejected', 'message', 'The action was not applied. Check your permissions and refresh the selected target.'),
    ('admin.outcome.succeeded', 'message', 'The action completed.'),
    ('appeal.accepted', 'message', 'Your appeal was accepted. You will be notified when access is restored.'),
    ('appeal.button.submit', 'button', 'Submit appeal'),
    ('appeal.in_review', 'message', 'Your appeal is being reviewed.'),
    ('appeal.prompt', 'message', 'Send /appeal followed by your explanation (up to 2000 characters). You can appeal once for this ban.'),
    ('appeal.rejected', 'message', 'Your appeal was not accepted. You cannot submit another appeal for this ban.'),
    ('appeal.submitted', 'message', 'Your appeal was received.'),
    ('appeal.title', 'message', 'Ban appeal'),
    ('error.admin.action_scope_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.admin.confirmation_invalid', 'error', 'This confirmation expired or does not match the action. Review the action again.'),
    ('error.admin.reason_invalid', 'error', 'Enter a reason of 1 to 1024 characters.'),
    ('error.admin.reviewer_unauthorized', 'error', 'This review action is not available to your admin account.'),
    ('error.admin.unauthorized', 'error', 'This action is not available to your admin account.'),
    ('error.appeal.reference_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.appeal.review_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.appeal.review_unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.appeal.text_invalid', 'error', 'Write an appeal of 1 to 2000 characters.'),
    ('error.appeal.unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.appeal.unban_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.appeal.unban_unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.m7.internal', 'error', 'The request could not be completed. Try again later.'),
    ('error.m7.invalid_request', 'error', 'Check your request and try again.'),
    ('error.m7.rate_limited', 'error', 'Too many requests. Please wait and try again.'),
    ('error.m7.stale_action', 'error', 'This action expired or changed. Open it again.'),
    ('error.m7.unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.account_action_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.account_action_unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.internal_block_unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.pair_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.photo_action_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.review_note_invalid', 'error', 'Review notes must contain at most 2000 characters.'),
    ('error.moderation.review_request_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.review_unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.reviewer_unauthorized', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.state_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.threshold_request_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.moderation.time_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.report.target_unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.report.text_invalid', 'error', 'Report details must contain at most 1024 characters.'),
    ('error.report.time_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.report.unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.support.admin_request_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.support.reference_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.support.state_invalid', 'error', 'This action is unavailable. Refresh and try again.'),
    ('error.support.text_invalid', 'error', 'Write a support message of 1 to 2000 characters.'),
    ('error.support.unanswered_limit', 'error', 'Please wait for a support reply before sending another message.'),
    ('error.support.unavailable', 'error', 'This action is unavailable. Refresh and try again.'),
    ('notification.account_unbanned.body', 'notification', 'The ban on your account has been removed.'),
    ('notification.account_unbanned.title', 'notification', 'Ban removed'),
    ('notification.account_unrestricted.body', 'notification', 'The restriction on your account has been removed.'),
    ('notification.account_unrestricted.title', 'notification', 'Restriction removed'),
    ('notification.ban_warning.body', 'notification', 'Your account has been banned. You can submit one appeal for this ban.'),
    ('notification.ban_warning.title', 'notification', 'Account banned'),
    ('notification.restriction_warning.body', 'notification', 'Your account is restricted while a safety review is completed. You can contact support.'),
    ('notification.restriction_warning.title', 'notification', 'Account restricted'),
    ('report.button.cancel', 'button', 'Cancel'),
    ('report.button.submit', 'button', 'Submit report'),
    ('report.prompt', 'message', 'Choose a reason for your report.'),
    ('report.reason.fake_profile', 'message', 'Fake profile'),
    ('report.reason.harassment', 'message', 'Harassment'),
    ('report.reason.inappropriate_photo', 'message', 'Inappropriate photo'),
    ('report.reason.offensive_behavior', 'message', 'Offensive behavior'),
    ('report.reason.other', 'message', 'Other'),
    ('report.reason.spam_or_scam', 'message', 'Spam or scam'),
    ('report.reason.under_18', 'message', 'Under 18'),
    ('report.submitted', 'message', 'Your report was received. Reports are confidential.'),
    ('report.text.prompt', 'message', 'Add details if you wish (up to 1024 characters).'),
    ('report.title', 'message', 'Report a concern'),
    ('support.button.open', 'button', 'Contact support'),
    ('support.button.send', 'button', 'Send message'),
    ('support.closed', 'message', 'This support conversation is closed.'),
    ('support.prompt', 'message', 'Send /support followed by your message (up to 2000 characters).'),
    ('support.sent', 'message', 'Your message was sent to support.'),
    ('support.title', 'message', 'Support'),
    ('support.waiting', 'message', 'Please wait for a reply before sending another message.')
)
INSERT INTO catalog.ui_texts (id, locale_code, text_key, value, category, variables, is_active, created_at, updated_at)
SELECT md5('en:' || text_key)::uuid, 'en', text_key, body, category, '[]'::jsonb, true,
  '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z' FROM seed;
