-- English source text for M6 Chat. User-authored chat text is never localized.
WITH seed(text_key, category, body) AS (
  VALUES
    ('chat.prompt.set.relationship_intent.title', 'message', 'Relationship intent'),
    ('chat.prompt.relationship_intent.question', 'message', 'What are you looking for here?'),
    ('chat.prompt.relationship_intent.answer.serious_relationship', 'message', 'Serious relationship'),
    ('chat.prompt.relationship_intent.answer.something_casual', 'message', 'Something casual'),
    ('chat.prompt.relationship_intent.answer.friendship', 'message', 'Friendship'),
    ('chat.prompt.relationship_intent.answer.marriage', 'message', 'Marriage'),
    ('chat.prompt.relationship_intent.answer.still_figuring_it_out', 'message', 'Still figuring it out'),
    ('chat.prompt.set.ideal_first_date.title', 'message', 'Ideal first date'),
    ('chat.prompt.ideal_first_date.question', 'message', 'What sounds like an ideal first date?'),
    ('chat.prompt.ideal_first_date.answer.coffee_and_conversation', 'message', 'Coffee and conversation'),
    ('chat.prompt.ideal_first_date.answer.walk_outdoors', 'message', 'A walk outdoors'),
    ('chat.prompt.ideal_first_date.answer.dinner', 'message', 'Dinner'),
    ('chat.prompt.ideal_first_date.answer.fun_activity', 'message', 'A fun activity'),
    ('chat.prompt.ideal_first_date.answer.surprise_me', 'message', 'Surprise me'),
    ('chat.prompt.set.chat_frequency.title', 'message', 'Chat frequency'),
    ('chat.prompt.chat_frequency.question', 'message', 'How often do you like to chat?'),
    ('chat.prompt.chat_frequency.answer.throughout_the_day', 'message', 'Throughout the day'),
    ('chat.prompt.chat_frequency.answer.few_times_a_day', 'message', 'A few times a day'),
    ('chat.prompt.chat_frequency.answer.one_daily_check_in', 'message', 'One daily check-in'),
    ('chat.prompt.chat_frequency.answer.whenever_both_free', 'message', 'Whenever we are both free'),
    ('chat.prompt.set.social_energy.title', 'message', 'Social energy'),
    ('chat.prompt.social_energy.question', 'message', 'How would you describe your social energy?'),
    ('chat.prompt.social_energy.answer.introvert', 'message', 'Introvert'),
    ('chat.prompt.social_energy.answer.mostly_introvert', 'message', 'Mostly introvert'),
    ('chat.prompt.social_energy.answer.a_mix', 'message', 'A mix'),
    ('chat.prompt.social_energy.answer.mostly_extrovert', 'message', 'Mostly extrovert'),
    ('chat.prompt.social_energy.answer.extrovert', 'message', 'Extrovert'),
    ('chat.prompt.set.weekend_habits.title', 'message', 'Weekend habits'),
    ('chat.prompt.weekend_habits.question', 'message', 'What does your ideal weekend look like?'),
    ('chat.prompt.weekend_habits.answer.staying_in', 'message', 'Staying in'),
    ('chat.prompt.weekend_habits.answer.friends_or_family', 'message', 'Friends or family'),
    ('chat.prompt.weekend_habits.answer.exploring_the_city', 'message', 'Exploring the city'),
    ('chat.prompt.weekend_habits.answer.nature_or_adventure', 'message', 'Nature or adventure'),
    ('chat.prompt.weekend_habits.answer.working_on_hobbies', 'message', 'Working on hobbies'),
    ('chat.prompt.set.calls_or_texting.title', 'message', 'Calls or texting'),
    ('chat.prompt.calls_or_texting.question', 'message', 'How do you prefer to communicate?'),
    ('chat.prompt.calls_or_texting.answer.mostly_text', 'message', 'Mostly text'),
    ('chat.prompt.calls_or_texting.answer.mostly_calls', 'message', 'Mostly calls'),
    ('chat.prompt.calls_or_texting.answer.a_mix', 'message', 'A mix'),
    ('chat.prompt.calls_or_texting.answer.voice_messages', 'message', 'Voice messages'),
    ('chat.prompt.calls_or_texting.answer.it_depends', 'message', 'It depends'),
    ('chat.prompt.set.important_values.title', 'message', 'Important values'),
    ('chat.prompt.important_values.question', 'message', 'Which value matters most to you?'),
    ('chat.prompt.important_values.answer.honesty', 'message', 'Honesty'),
    ('chat.prompt.important_values.answer.kindness', 'message', 'Kindness'),
    ('chat.prompt.important_values.answer.ambition', 'message', 'Ambition'),
    ('chat.prompt.important_values.answer.family', 'message', 'Family'),
    ('chat.prompt.important_values.answer.humor', 'message', 'Humor'),
    ('chat.prompt.set.meeting_in_person.title', 'message', 'Meeting in person'),
    ('chat.prompt.meeting_in_person.question', 'message', 'When would you feel comfortable meeting?'),
    ('chat.prompt.meeting_in_person.answer.after_a_few_good_conversations', 'message', 'After a few good conversations'),
    ('chat.prompt.meeting_in_person.answer.within_a_week', 'message', 'Within a week'),
    ('chat.prompt.meeting_in_person.answer.prefer_more_time', 'message', 'I prefer to take more time'),
    ('chat.prompt.meeting_in_person.answer.video_call_first', 'message', 'Video call first'),
    ('chat.prompt.set.relationship_pace.title', 'message', 'Relationship pace'),
    ('chat.prompt.relationship_pace.question', 'message', 'What relationship pace feels right?'),
    ('chat.prompt.relationship_pace.answer.slow_and_steady', 'message', 'Slow and steady'),
    ('chat.prompt.relationship_pace.answer.let_it_happen_naturally', 'message', 'Let it happen naturally'),
    ('chat.prompt.relationship_pace.answer.intentional_and_fast', 'message', 'Intentional and fast'),
    ('chat.prompt.relationship_pace.answer.it_depends_on_connection', 'message', 'It depends on the connection'),
    ('chat.prompt.set.current_life_focus.title', 'message', 'Current life focus'),
    ('chat.prompt.current_life_focus.question', 'message', 'What is your main focus right now?'),
    ('chat.prompt.current_life_focus.answer.career_or_studies', 'message', 'Career or studies'),
    ('chat.prompt.current_life_focus.answer.family', 'message', 'Family'),
    ('chat.prompt.current_life_focus.answer.health_and_growth', 'message', 'Health and growth'),
    ('chat.prompt.current_life_focus.answer.fun_and_new_experiences', 'message', 'Fun and new experiences'),
    ('chat.prompt.current_life_focus.answer.finding_balance', 'message', 'Finding balance'),
    ('chat.title', 'message', 'Chat'),
    ('chat.empty', 'message', 'No messages yet. Start with a question.'),
    ('chat.locked', 'message', 'Start with a question or unlock text chat.'),
    ('chat.unlocked', 'message', 'Text chat is unlocked.'),
    ('chat.text.prompt', 'message', 'Write a message'),
    ('chat.status.muted', 'message', 'Chat muted.'),
    ('chat.status.closed', 'message', 'This chat is closed.'),
    ('chat.read.updated', 'message', 'Chat marked as read.'),
    ('chat.button.questions', 'button', 'Ask a question'),
    ('chat.button.unlock', 'button', 'Unlock text chat'),
    ('chat.button.mute', 'button', 'Mute chat'),
    ('chat.button.unmute', 'button', 'Unmute chat'),
    ('chat.button.unmatch', 'button', 'Unmatch'),
    ('chat.button.mark_read', 'button', 'Mark as read'),
    ('notification.new_chat_message.title', 'notification', 'New message'),
    ('notification.new_chat_message.body', 'notification', 'You have a new message in Nakh.'),
    ('notification.chat_closed.title', 'notification', 'Chat closed'),
    ('notification.chat_closed.body', 'notification', 'This Match and chat have ended.'),
    ('error.chat.cleanup_batch_invalid', 'error', 'Chat cleanup could not be scheduled safely.'),
    ('error.chat.cleanup_state_invalid', 'error', 'Chat cleanup found an invalid state.'),
    ('error.chat.cursor_invalid', 'error', 'This chat page expired. Open the chat again.'),
    ('error.chat.snapshot_conflict', 'error', 'Report evidence conflicts with an earlier request.'),
    ('error.chat.snapshot_invalid', 'error', 'Report evidence could not be captured safely.'),
    ('error.chat.text_invalid', 'error', 'Write a message of 1 to 1000 characters.'),
    ('error.chat.text_unavailable', 'error', 'Unlock text chat before sending a message.'),
    ('error.chat.unavailable', 'error', 'This chat is no longer available.'),
    ('error.chat.unmatch_time_invalid', 'error', 'This unmatch time is invalid.'),
    ('error.chat.unmatch_window_invalid', 'error', 'The report window for this unmatch is invalid.'),
    ('error.chat.version_conflict', 'error', 'This chat changed. Refresh and try again.'),
    ('error.notification.delivery_state_invalid', 'error', 'This notification delivery state is invalid.'),
    ('error.notification.delivery_time_invalid', 'error', 'This notification delivery time is invalid.')
)
INSERT INTO catalog.ui_texts (
  id, locale_code, text_key, value, category, variables, is_active, created_at, updated_at
)
SELECT md5('en:' || text_key)::uuid, 'en', text_key, body, category, '[]'::jsonb, true,
  '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z'
FROM seed;

COMMENT ON TABLE chat.chat_messages IS
  'M6 typed chat history. User-authored text is immutable, sensitive, and never a localization template.';
