-- English source text for the M5 Nakh lifecycle. User-authored Nakh prose is never localized.
WITH seed(text_key, category, body, variables) AS (
  VALUES
    ('nakh.compose.title', 'message', 'Send Nakh', '[]'),
    ('nakh.compose.prompt', 'message', 'Write a private opening message.', '[]'),
    ('nakh.compose.cost.credits', 'payment', 'Send for 2 credits', '[]'),
    ('nakh.compose.cost.stars', 'payment', 'Send for 2 Telegram Stars', '[]'),
    ('nakh.compose.auto_settle_consent', 'payment', 'If you receive enough credits later, this Pending Nakh will be sent automatically.', '[]'),
    ('nakh.button.send_credits', 'button', 'Send with credits', '[]'),
    ('nakh.button.pay_stars', 'button', 'Pay with Telegram Stars', '[]'),
    ('nakh.button.save_pending', 'button', 'Save as Pending Nakh', '[]'),
    ('nakh.pending.title', 'message', 'Pending Nakhes', '[]'),
    ('nakh.pending.empty', 'message', 'You have no Pending Nakhes.', '[]'),
    ('nakh.pending.card.title', 'message', 'Pending Nakh for {name}', '["name"]'),
    ('nakh.pending.card.expires', 'message', 'Expires {expiresAt}', '["expiresAt"]'),
    ('nakh.pending.created', 'message', 'Your Pending Nakh was saved.', '[]'),
    ('nakh.pending.edited', 'message', 'Your Pending Nakh was updated.', '[]'),
    ('nakh.pending.cancelled_like', 'message', 'Pending Nakh cancelled and Like sent.', '[]'),
    ('nakh.pending.cancelled_not_interested', 'message', 'Pending Nakh cancelled and marked Not interested.', '[]'),
    ('nakh.pending.expired', 'message', 'This Pending Nakh expired before payment.', '[]'),
    ('nakh.pending.closed', 'message', 'This Pending Nakh is no longer available.', '[]'),
    ('nakh.pending.button.edit', 'button', 'Edit message', '[]'),
    ('nakh.pending.button.cancel', 'button', 'Cancel Pending Nakh', '[]'),
    ('nakh.pending.button.convert_like', 'button', 'Cancel and send Like', '[]'),
    ('nakh.pending.button.convert_not_interested', 'button', 'Cancel and mark Not interested', '[]'),
    ('nakh.sent.title', 'message', 'Sent Nakhes', '[]'),
    ('nakh.sent.empty', 'message', 'You have not sent any Nakhes.', '[]'),
    ('nakh.received.title', 'message', 'Received Nakhes', '[]'),
    ('nakh.received.empty', 'message', 'You have no received Nakhes.', '[]'),
    ('nakh.received.card.title', 'message', 'Nakh from {name}', '["name"]'),
    ('nakh.received.message_label', 'message', 'Opening message', '[]'),
    ('nakh.received.button.view_profile', 'button', 'View Profile', '[]'),
    ('nakh.received.button.accept', 'button', 'Accept', '[]'),
    ('nakh.received.button.reject', 'button', 'Close', '[]'),
    ('nakh.received.button.report', 'button', 'Report', '[]'),
    ('nakh.status.sent', 'message', 'Sent', '[]'),
    ('nakh.status.seen', 'message', 'Seen', '[]'),
    ('nakh.status.accepted', 'message', 'Accepted', '[]'),
    ('nakh.status.rejected', 'message', 'Closed', '[]'),
    ('nakh.status.expired', 'message', 'Expired', '[]'),
    ('nakh.status.closed', 'message', 'Closed', '[]'),
    ('nakh.delivery.sent', 'message', 'Your Nakh was sent.', '[]'),
    ('nakh.action.accepted', 'message', 'Nakh accepted. You matched!', '[]'),
    ('nakh.action.rejected', 'message', 'This Nakh is closed.', '[]'),
    ('notification.nakh_received.title', 'notification', 'New Nakh', '[]'),
    ('notification.nakh_received.body', 'notification', 'Someone sent you a Nakh.', '[]'),
    ('notification.pending_nakh_payment_reminder.title', 'notification', 'Pending Nakh', '[]'),
    ('notification.pending_nakh_payment_reminder.body', 'notification', 'Your Pending Nakh still needs payment before it can be sent.', '[]'),
    ('error.nakh.text_invalid', 'error', 'Write a message of 1 to 240 characters.', '[]'),
    ('error.nakh.time_invalid', 'error', 'This Nakh time is invalid.', '[]'),
    ('error.nakh.pending_count_invalid', 'error', 'Your Pending Nakh count is invalid.', '[]'),
    ('error.nakh.reminder_state_invalid', 'error', 'This Pending Nakh reminder is invalid.', '[]'),
    ('error.nakh.balance_invalid', 'error', 'Your credit balance is invalid.', '[]'),
    ('error.nakh.fifo_order_invalid', 'error', 'Pending Nakhes could not be ordered safely.', '[]'),
    ('error.nakh.cursor_invalid', 'error', 'This Nakhes page expired. Open Nakhes again.', '[]'),
    ('error.nakh.page_limit_invalid', 'error', 'This Nakhes page size is invalid.', '[]'),
    ('error.nakh.unavailable', 'error', 'This Nakh is no longer available.', '[]'),
    ('error.nakh.flow_exists', 'error', 'You already started a Nakh for this person.', '[]'),
    ('error.nakh.quota_reached', 'error', 'You can have at most five unpaid Pending Nakhes.', '[]'),
    ('error.nakh.version_conflict', 'error', 'This Nakh changed. Refresh and try again.', '[]'),
    ('error.nakh.terminal', 'error', 'This Nakh is already closed.', '[]'),
    ('error.nakh.not_found', 'error', 'This Nakh was not found.', '[]'),
    ('error.nakh.action_conflict', 'error', 'This Nakh action was already completed.', '[]'),
    ('error.nakh.payment_pending', 'error', 'This Nakh payment is still pending.', '[]'),
    ('error.nakh.payment_expired', 'error', 'This Nakh payment expired.', '[]'),
    ('error.nakh.funding_invalid', 'error', 'This Nakh funding could not be verified.', '[]'),
    ('error.nakh.settlement_invalid', 'error', 'Pending Nakhes could not be settled safely.', '[]')
)
INSERT INTO catalog.ui_texts (
  id, locale_code, text_key, value, category, variables, is_active, created_at, updated_at
)
SELECT md5('en:' || text_key)::uuid, 'en', text_key, body, category, variables::jsonb, true,
  '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z'
FROM seed;

COMMENT ON SCHEMA nakh IS
  'M5 Nakh lifecycle data. User-authored Nakh text is stored verbatim after validation and is never a localization template.';

