import type { LocalizationManifestEntry } from './m1-catalog.js';

/** English fallback for M7; restricted user and admin text is never a template variable. */
export const M7_LOCALIZATION_ENTRIES: readonly LocalizationManifestEntry[] = [
  {
    key: 'admin.button.cancel',
    category: 'button',
    english: 'Cancel',
    variables: [],
    required: true,
  },
  {
    key: 'admin.button.confirm',
    category: 'button',
    english: 'Confirm action',
    variables: [],
    required: true,
  },
  {
    key: 'admin.confirm.prompt',
    category: 'message',
    english: 'Check the selected target and reason before confirming.',
    variables: [],
    required: true,
  },
  {
    key: 'admin.confirm.title',
    category: 'message',
    english: 'Confirm this action',
    variables: [],
    required: true,
  },
  {
    key: 'admin.outcome.failed',
    category: 'message',
    english: 'The action could not be completed. Try again later.',
    variables: [],
    required: true,
  },
  {
    key: 'admin.outcome.rejected',
    category: 'message',
    english: 'The action was not applied. Check your permissions and refresh the selected target.',
    variables: [],
    required: true,
  },
  {
    key: 'admin.outcome.succeeded',
    category: 'message',
    english: 'The action completed.',
    variables: [],
    required: true,
  },
  {
    key: 'appeal.accepted',
    category: 'message',
    english: 'Your appeal was accepted. You will be notified when access is restored.',
    variables: [],
    required: true,
  },
  {
    key: 'appeal.button.submit',
    category: 'button',
    english: 'Submit appeal',
    variables: [],
    required: true,
  },
  {
    key: 'appeal.in_review',
    category: 'message',
    english: 'Your appeal is being reviewed.',
    variables: [],
    required: true,
  },
  {
    key: 'appeal.prompt',
    category: 'message',
    english:
      'Send /appeal followed by your explanation (up to 2000 characters). You can appeal once for this ban.',
    variables: [],
    required: true,
  },
  {
    key: 'appeal.rejected',
    category: 'message',
    english: 'Your appeal was not accepted. You cannot submit another appeal for this ban.',
    variables: [],
    required: true,
  },
  {
    key: 'appeal.submitted',
    category: 'message',
    english: 'Your appeal was received.',
    variables: [],
    required: true,
  },
  {
    key: 'appeal.title',
    category: 'message',
    english: 'Ban appeal',
    variables: [],
    required: true,
  },
  {
    key: 'error.admin.action_scope_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.admin.confirmation_invalid',
    category: 'error',
    english: 'This confirmation expired or does not match the action. Review the action again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.admin.reason_invalid',
    category: 'error',
    english: 'Enter a reason of 1 to 1024 characters.',
    variables: [],
    required: true,
  },
  {
    key: 'error.admin.reviewer_unauthorized',
    category: 'error',
    english: 'This review action is not available to your admin account.',
    variables: [],
    required: true,
  },
  {
    key: 'error.admin.unauthorized',
    category: 'error',
    english: 'This action is not available to your admin account.',
    variables: [],
    required: true,
  },
  {
    key: 'error.appeal.reference_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.appeal.review_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.appeal.review_unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.appeal.text_invalid',
    category: 'error',
    english: 'Write an appeal of 1 to 2000 characters.',
    variables: [],
    required: true,
  },
  {
    key: 'error.appeal.unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.appeal.unban_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.appeal.unban_unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.m7.internal',
    category: 'error',
    english: 'The request could not be completed. Try again later.',
    variables: [],
    required: true,
  },
  {
    key: 'error.m7.invalid_request',
    category: 'error',
    english: 'Check your request and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.m7.rate_limited',
    category: 'error',
    english: 'Too many requests. Please wait and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.m7.stale_action',
    category: 'error',
    english: 'This action expired or changed. Open it again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.m7.unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.account_action_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.account_action_unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.internal_block_unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.pair_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.photo_action_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.review_note_invalid',
    category: 'error',
    english: 'Review notes must contain at most 2000 characters.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.review_request_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.review_unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.reviewer_unauthorized',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.state_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.threshold_request_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.moderation.time_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.report.target_unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.report.text_invalid',
    category: 'error',
    english: 'Report details must contain at most 1024 characters.',
    variables: [],
    required: true,
  },
  {
    key: 'error.report.time_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.report.unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.support.admin_request_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.support.reference_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.support.state_invalid',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'error.support.text_invalid',
    category: 'error',
    english: 'Write a support message of 1 to 2000 characters.',
    variables: [],
    required: true,
  },
  {
    key: 'error.support.unanswered_limit',
    category: 'error',
    english: 'Please wait for a support reply before sending another message.',
    variables: [],
    required: true,
  },
  {
    key: 'error.support.unavailable',
    category: 'error',
    english: 'This action is unavailable. Refresh and try again.',
    variables: [],
    required: true,
  },
  {
    key: 'notification.account_unbanned.body',
    category: 'notification',
    english: 'The ban on your account has been removed.',
    variables: [],
    required: true,
  },
  {
    key: 'notification.account_unbanned.title',
    category: 'notification',
    english: 'Ban removed',
    variables: [],
    required: true,
  },
  {
    key: 'notification.account_unrestricted.body',
    category: 'notification',
    english: 'The restriction on your account has been removed.',
    variables: [],
    required: true,
  },
  {
    key: 'notification.account_unrestricted.title',
    category: 'notification',
    english: 'Restriction removed',
    variables: [],
    required: true,
  },
  {
    key: 'notification.ban_warning.body',
    category: 'notification',
    english: 'Your account has been banned. You can submit one appeal for this ban.',
    variables: [],
    required: true,
  },
  {
    key: 'notification.ban_warning.title',
    category: 'notification',
    english: 'Account banned',
    variables: [],
    required: true,
  },
  {
    key: 'notification.restriction_warning.body',
    category: 'notification',
    english:
      'Your account is restricted while a safety review is completed. You can contact support.',
    variables: [],
    required: true,
  },
  {
    key: 'notification.restriction_warning.title',
    category: 'notification',
    english: 'Account restricted',
    variables: [],
    required: true,
  },
  {
    key: 'report.button.cancel',
    category: 'button',
    english: 'Cancel',
    variables: [],
    required: true,
  },
  {
    key: 'report.button.submit',
    category: 'button',
    english: 'Submit report',
    variables: [],
    required: true,
  },
  {
    key: 'report.prompt',
    category: 'message',
    english: 'Choose a reason for your report.',
    variables: [],
    required: true,
  },
  {
    key: 'report.reason.fake_profile',
    category: 'message',
    english: 'Fake profile',
    variables: [],
    required: true,
  },
  {
    key: 'report.reason.harassment',
    category: 'message',
    english: 'Harassment',
    variables: [],
    required: true,
  },
  {
    key: 'report.reason.inappropriate_photo',
    category: 'message',
    english: 'Inappropriate photo',
    variables: [],
    required: true,
  },
  {
    key: 'report.reason.offensive_behavior',
    category: 'message',
    english: 'Offensive behavior',
    variables: [],
    required: true,
  },
  {
    key: 'report.reason.other',
    category: 'message',
    english: 'Other',
    variables: [],
    required: true,
  },
  {
    key: 'report.reason.spam_or_scam',
    category: 'message',
    english: 'Spam or scam',
    variables: [],
    required: true,
  },
  {
    key: 'report.reason.under_18',
    category: 'message',
    english: 'Under 18',
    variables: [],
    required: true,
  },
  {
    key: 'report.submitted',
    category: 'message',
    english: 'Your report was received. Reports are confidential.',
    variables: [],
    required: true,
  },
  {
    key: 'report.text.prompt',
    category: 'message',
    english: 'Add details if you wish (up to 1024 characters).',
    variables: [],
    required: true,
  },
  {
    key: 'report.title',
    category: 'message',
    english: 'Report a concern',
    variables: [],
    required: true,
  },
  {
    key: 'support.button.open',
    category: 'button',
    english: 'Contact support',
    variables: [],
    required: true,
  },
  {
    key: 'support.button.send',
    category: 'button',
    english: 'Send message',
    variables: [],
    required: true,
  },
  {
    key: 'support.closed',
    category: 'message',
    english: 'This support conversation is closed.',
    variables: [],
    required: true,
  },
  {
    key: 'support.prompt',
    category: 'message',
    english: 'Send /support followed by your message (up to 2000 characters).',
    variables: [],
    required: true,
  },
  {
    key: 'support.sent',
    category: 'message',
    english: 'Your message was sent to support.',
    variables: [],
    required: true,
  },
  {
    key: 'support.title',
    category: 'message',
    english: 'Support',
    variables: [],
    required: true,
  },
  {
    key: 'support.waiting',
    category: 'message',
    english: 'Please wait for a reply before sending another message.',
    variables: [],
    required: true,
  },
];
