DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM (VALUES
    ('admin.button.cancel'),
    ('admin.button.confirm'),
    ('admin.confirm.prompt'),
    ('admin.confirm.title'),
    ('admin.outcome.failed'),
    ('admin.outcome.rejected'),
    ('admin.outcome.succeeded'),
    ('appeal.accepted'),
    ('appeal.button.submit'),
    ('appeal.in_review'),
    ('appeal.prompt'),
    ('appeal.rejected'),
    ('appeal.submitted'),
    ('appeal.title'),
    ('error.admin.action_scope_invalid'),
    ('error.admin.confirmation_invalid'),
    ('error.admin.reason_invalid'),
    ('error.admin.reviewer_unauthorized'),
    ('error.admin.unauthorized'),
    ('error.appeal.reference_invalid'),
    ('error.appeal.review_invalid'),
    ('error.appeal.review_unavailable'),
    ('error.appeal.text_invalid'),
    ('error.appeal.unavailable'),
    ('error.appeal.unban_invalid'),
    ('error.appeal.unban_unavailable'),
    ('error.m7.internal'),
    ('error.m7.invalid_request'),
    ('error.m7.rate_limited'),
    ('error.m7.stale_action'),
    ('error.m7.unavailable'),
    ('error.moderation.account_action_invalid'),
    ('error.moderation.account_action_unavailable'),
    ('error.moderation.internal_block_unavailable'),
    ('error.moderation.pair_invalid'),
    ('error.moderation.photo_action_invalid'),
    ('error.moderation.review_note_invalid'),
    ('error.moderation.review_request_invalid'),
    ('error.moderation.review_unavailable'),
    ('error.moderation.reviewer_unauthorized'),
    ('error.moderation.state_invalid'),
    ('error.moderation.threshold_request_invalid'),
    ('error.moderation.time_invalid'),
    ('error.report.target_unavailable'),
    ('error.report.text_invalid'),
    ('error.report.time_invalid'),
    ('error.report.unavailable'),
    ('error.support.admin_request_invalid'),
    ('error.support.reference_invalid'),
    ('error.support.state_invalid'),
    ('error.support.text_invalid'),
    ('error.support.unanswered_limit'),
    ('error.support.unavailable'),
    ('notification.account_unbanned.body'),
    ('notification.account_unbanned.title'),
    ('notification.account_unrestricted.body'),
    ('notification.account_unrestricted.title'),
    ('notification.ban_warning.body'),
    ('notification.ban_warning.title'),
    ('notification.restriction_warning.body'),
    ('notification.restriction_warning.title'),
    ('report.button.cancel'),
    ('report.button.submit'),
    ('report.prompt'),
    ('report.reason.fake_profile'),
    ('report.reason.harassment'),
    ('report.reason.inappropriate_photo'),
    ('report.reason.offensive_behavior'),
    ('report.reason.other'),
    ('report.reason.spam_or_scam'),
    ('report.reason.under_18'),
    ('report.submitted'),
    ('report.text.prompt'),
    ('report.title'),
    ('support.button.open'),
    ('support.button.send'),
    ('support.closed'),
    ('support.prompt'),
    ('support.sent'),
    ('support.title'),
    ('support.waiting')
  ) required(text_key) WHERE NOT EXISTS (SELECT 1 FROM catalog.ui_texts t
    WHERE t.locale_code = 'en' AND t.text_key = required.text_key AND t.is_active
      AND t.variables = '[]'::jsonb AND length(t.value) > 0)) THEN
    RAISE EXCEPTION 'M7 English fallback catalog is incomplete';
  END IF;
  IF EXISTS (SELECT 1 FROM moderation.report_reasons r WHERE NOT EXISTS (
    SELECT 1 FROM catalog.ui_texts t WHERE t.locale_code = 'en' AND t.text_key = r.label_key AND t.is_active
  )) THEN RAISE EXCEPTION 'M7 report reason localization is incomplete'; END IF;
END $$;
